---
- hosts: all
  become: true

  tasks:
  - name: Stop the running container
    command: docker stop tony
    ignore_errors: yes

  - name: Remove stopped container
    command: docker rm -f tony
    ignore_errors: yes

  - name: Delete the image
    command: docker rmi corona:1.0
    ignore_errors: yes

  - name: lets pull dockerhub
    command: docker pull izmebalu/corona:1.0

  - name: Running the image
    command: docker run -d --name tony -p 8080:8080 izmebalu/corona:1.0
